name: devbundle
title: ArcGIS Developer Bundle
description: ArcGIS Developer Bundle ist die perfekte Kombination aus Innovation und Digitaler Souveränität.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
