# Generated documentation for module arcpy.management


class MultipartToSinglepart(object):
    """
    Creates a feature class containing singlepart features generated by separating multipart input features.
    """

    @property
    def description(self) -> str:
        return """

        MultipartToSinglepart_management(in_features, out_feature_class)

        Creates a feature class containing singlepart features generated by
        separating multipart input features.

     INPUTS:
      in_features (Feature Layer):
          The input features that can be any feature type.

     OUTPUTS:
      out_feature_class (Feature Class):
          The output feature class containing features that vary with input
          feature type.

        """