# Generated documentation for module arcpy.topographic


class ImportTopology(object):
    """
    Creates a geodatabase topology from a definition .xml file generated by the Export Topology tool in the Topographic Production toolbox.
    """

    @property
    def description(self) -> str:
        return """

        ImportTopology_topographic(in_feature_dataset, topology_definition_file)

        Creates a geodatabase topology from a definition .xml file generated
        by the Export Topology tool in the Topographic Production toolbox.

     INPUTS:
      in_feature_dataset (Feature Dataset):
          The feature dataset in which the topology will be created. The feature
          dataset must contain the feature classes listed in the
          topology_definition_file.
      topology_definition_file (File):
          The .xml file that contains the topology definition.

        """