# Generated documentation for module arcpy.indoorpositioning


class ComputePositioningQuality(object):
    """
    Populates an IPS Quality dataset generated by the Create IPS Quality Dataset tool.
    """

    @property
    def description(self) -> str:
        return """

        ComputePositioningQuality_indoorpositioning(target_ips_quality_dataset, in_ips_recordings_features, {in_sight_blocking_details_features})

        Populates an IPS Quality dataset generated by the Create IPS Quality
        Dataset tool.

     INPUTS:
      target_ips_quality_dataset (Dataset):
          The IPS Quality dataset generated by the Create IPS Quality Dataset
          tool that will be populated.
      in_ips_recordings_features (Feature Layer):
          The IPS Recordings feature layer that contains recordings collected
          using the ArcGIS IPS Setup app.
      in_sight_blocking_details_features {Feature Layer}:
          Details features from an Indoors dataset representing obstacles for
          line-of-sight calculation. It is recommended that you only use
          meaningful features, such as features that represent walls.

        """