# Generated documentation for module arcpy.indoorpositioning


class GenerateIndoorPositioningDataset(object):
    """
    Generates an Indoor Positioning Dataset for an existing ArcGIS IPS installation. You can use a survey-based or survey-less method to generate the dataset.
    """

    @property
    def description(self) -> str:
        return """

        GenerateIndoorPositioningDataset_indoorpositioning(target_ips_positioning_datasets, dataset_name, generation_method, in_levels, {in_ips_recordings}, {in_beacons}, {in_ips_areas}, {in_walls})

        Generates an Indoor Positioning Dataset for an existing ArcGIS IPS
        installation. You can use a survey-based or survey-less method to
        generate the dataset.

     INPUTS:
      target_ips_positioning_datasets (Feature Layer):
          The feature class where the generated Indoor Positioning Dataset will
          be stored.
      dataset_name (String):
          The name of the Indoor Positioning Dataset. To generate
          a new Indoor Positioning Dataset, provide a unique name.To
          update an existing Indoor Positioning Dataset, provide the name of
          the existing dataset. A new dataset will be created by combining the
          existing dataset and the tool inputs. Updating the dataset is only
          available when the generation_method parameter is set to SURVEY_BASED.
      generation_method (String):
          Specifies the method that will be used to generate the Indoor
          Positioning Dataset.SURVEY_BASED-The dataset will be generated by
          processing IPS
          Recordings.SURVEY_LESS-The dataset will be generated by simulating the
          Bluetooth
          signal propagation through the indoor environment.
      in_levels (Feature Layer):
          The polygon features representing Level footprints within the
          facilities.
      in_ips_recordings {Feature Layer}:
          The feature class or feature service that contains IPS Setup survey
          recordings.This parameter is required when the generation_method
          parameter is set
          to SURVEY_BASED.
      in_beacons {Feature Layer}:
          The point features representing the position and settings of Bluetooth
          beacons deployed in the indoor environment.This parameter is required
          when the generation_method parameter is set
          to SURVEY_LESS.
      in_ips_areas {Feature Layer}:
          The polygon features representing the area where the Indoor
          Positioning Dataset will be generated.This parameter is required when
          the generation_method parameter is set
          to SURVEY_LESS.
      in_walls {Feature Layer}:
          The polygon features representing the physical extent of walls.This
          parameter is required when the generation_method parameter is set
          to SURVEY_LESS.

        """