# Generated documentation for module arcpy.stpm


class VisualizeSpaceTimeCube2D(object):
    """
    Visualizes the variables stored in a netCDF space-time cube and the results generated by the Space Time Pattern Mining tools. Output from this tool is a two-dimensional representation uniquely rendered based on the variable and theme specified.
    """

    @property
    def description(self) -> str:
        return """

        VisualizeSpaceTimeCube2D_stpm(in_cube, cube_variable, display_theme, output_features, {enable_time_series_popups})

        Visualizes the variables stored in a netCDF space-time cube and the
        results generated by the Space Time Pattern Mining tools. Output from
        this tool is a two-dimensional representation uniquely rendered based
        on the variable and theme specified.

     INPUTS:
      in_cube (File):
          The space-time cube containing the variable to be analyzed. Space-time
          cubes have a .nc file extension and are created using various tools in
          the Space Time Pattern Mining toolbox.
      cube_variable (String):
          The numeric variable in the netCDF cube that will be explored.
          The space-time cube will always contain the COUNT variable.
          Anyorvalues will also be available if they were included when the cube
          was created. Summary FieldsVariables
      display_theme (String):
          Specifies the characteristic of thevalue that will be
          displayed. Available options depend on how the cube was created and
          the analyses that were run. Cube VariableFor in-depth
          information about each option, including descriptions of
          the output and created charts, see the Visualization display themes
          for the space-time cube topic.LOCATIONS_WITH_DATA-All locations that
          contain data for the cube
          variable parameter will be displayed.TRENDS-The trend of values at
          each location that were determined using
          the Mann-Kendall statistic will be
          displayed.HOT_AND_COLD_SPOT_TRENDS-The trend of z-scores at each
          location that
          were determined using the Mann-Kendall statistic will be
          displayed.EMERGING_HOT_SPOT_ANALYSIS_RESULTS-The results of the
          Emerging Hot
          Spot Analysis tool will be
          displayed.LOCAL_OUTLIER_ANALYSIS_RESULTS-The results of the Local
          Outlier
          Analysis tool will be displayed.PERCENTAGE_OF_LOCAL_OUTLIERS-The total
          percentage of outliers at each
          location will be
          displayed.LOCAL_OUTLIER_IN_MOST_RECENT_TIME_PERIOD-The outliers
          occurring in the
          most recent time period will be
          displayed.TIME_SERIES_CLUSTERING_RESULTS-The results of the Time
          Series
          Clustering tool will be
          displayed.LOCATIONS_WITHOUT_SPATIAL_NEIGHBORS-Locations that have no
          spatial
          neighbors for the last analysis run will be displayed. These locations
          rely only on temporal neighbors for
          analysis.NUMBER_OF_ESTIMATED_BINS-The number of bins that were
          estimated for
          each location will be displayed.LOCATIONS_EXCLUDED_FROM_ANALYSIS-The
          locations that were excluded from
          analysis because they had empty bins that did not meet the criteria
          for estimation will be displayed.FORECAST_RESULTS-The results of a
          tool in the Time Series Forecasting
          toolset will be displayed.TIME_SERIES_OUTLIER_RESULTS-The results of
          the outlier option
          parameter in the Time Series Forecasting tools will be
          displayed.TIME_SERIES_CHANGE_POINTS-The results of the Change Point
          Detection
          tool will be displayed.TIME_SERIES_CROSS_CORRELATION_RESULTS-The
          results of the Time Series
          Cross Correlation tool will be displayed.
      enable_time_series_popups {Boolean}:
          Specifies whether time series pop-ups will be generated for each
          output feature. Pop-up charts are not supported for shapefile
          outputs.CREATE_POPUP-Time series pop-ups will be generated for each
          feature in
          the dataset.NO_POPUP-Time series pop-ups will not be generated. This
          is the
          default.

     OUTPUTS:
      output_features (Feature Class):
          The output feature class results. This feature class will be a two-
          dimensional map representation of the specified display variable.

        """