# Generated documentation for module arcpy.locref


class CreateLRSNetworkFromExistingDataset(object):
    """
    Creates an LRS Network using an existing polyline feature class.
    """

    @property
    def description(self) -> str:
        return """

        CreateLRSNetworkFromExistingDataset_locref(in_feature_class, lrs_name, route_id_field, {route_name_field}, from_date_field, to_date_field, {derive_from_line_network}, {line_network_name}, {include_fields_to_support_lines}, {line_id_field}, {line_name_field}, {line_order_field}, {route_id_configuration}, {individual_route_id_fields;individual_route_id_fields...})

        Creates an LRS Network using an existing polyline feature class.

     INPUTS:
      in_feature_class (Feature Layer):
          The input feature class that will be registered as the LRS Network.
          The name of the feature class must be 26 or fewer characters. The
          feature class must reside in a geodatabase that contains an LRS. The
          name of this feature class will be used as the name of the LRS
          Network.
      lrs_name (String):
          The LRS name to which the new LRS Network will be registered. The LRS
          must reside in the same geodatabase as the in_feature_class value.
      route_id_field (Field):
          The field in the in_feature_class value that will be mapped as the LRS
          Network route ID. This must be a string or GUID field type.
      route_name_field {Field}:
          A string field in the in_feature_class value that will be mapped as
          the LRS Network route name.
      from_date_field (Field):
          A date field in the in_feature_class value that will be mapped as the
          LRS Network from date.
      to_date_field (Field):
          A date field in the in_feature_class value that will be mapped as the
          LRS Network to date.
      derive_from_line_network {Boolean}:
          Specifies whether the network will be configured as an LRS derived
          network.DERIVE-The output of this tool will be an LRS derived network.
          The
          line_network_name parameter must also be provided.DO_NOT_DERIVE-The
          output of this tool will not be an LRS derived
          network. This is the default.
      line_network_name {String}:
          The name of the LRS line network to which the output LRS derived
          network will be registered. The input LRS line network must reside in
          the same geodatabase workspace as the in_feature_class value. This
          parameter is only used if the derive_from_line_network parameter value
          is set to DERIVE.
      include_fields_to_support_lines {Boolean}:
          Specifies whether the network will be configured to support
          lines.INCLUDE-The output of this tool will be an LRS line network. The
          line_id_field, line_name_field, and line_order_field parameters must
          also be provided.DO_NOT_INCLUDE-The output of this tool will not be
          an LRS line
          network. This is the default.
      line_id_field {Field}:
          The field in the in_feature_class value that will be mapped as the LRS
          Network line ID. This parameter is only used if the
          include_fields_to_support_lines parameter value is set to INCLUDE.
          This must be a string or GUID field type and must match the field type
          and length of the route ID field in the centerline sequence table.
      line_name_field {Field}:
          A string field in the in_feature_class value that will be mapped as
          the LRS Network line name. This parameter is only used if the
          include_fields_to_support_lines parameter value is set to INCLUDE.
      line_order_field {Field}:
          An integer field in the in_feature_class value that will be mapped as
          the LRS Network line order. This parameter is only used if the
          include_fields_to_support_lines parameter value is set to INCLUDE.
      route_id_configuration {String}:
          Specifies the route ID configuration for the LRS
          Network.AUTOGENERATED_ROUTE_ID-The route ID field will be an
          automatically
          generated GUID. The route name can be configured as an LRS field. This
          is the default.SINGLE_FIELD_ROUTE_ID-The route ID field will be a
          single user-
          generated field. Only nonline networks are
          supported.MULTI_FIELD_ROUTE_ID-The route ID field will be a user-
          generated field
          concatenated from more than one field to form the route ID. Only
          nonline networks are supported.
      individual_route_id_fields {Field}:
          The individual fields in the in_feature_class value that will be used
          to form the route ID. This parameter is only used if the
          route_id_configuration parameter value is set to MULTI_FIELD_ROUTE_ID.
          The fields must be either string or integer field types.

        """