# Generated documentation for module arcpy.locref


class ModifyLRSNetwork(object):
    """
    Modifies an LRS Network in a Location Referencing linear referencing system (LRS).
    """

    @property
    def description(self) -> str:
        return """

        ModifyLRSNetwork_locref(in_feature_class, {route_id_field}, {route_name_field}, {from_date_field}, {to_date_field}, {derive_from_line_network}, {line_network_name}, {include_fields_to_support_lines}, {line_id_field}, {line_name_field}, {line_order_field}, {route_id_configuration}, {individual_route_id_fields;individual_route_id_fields...})

        Modifies an LRS Network in a Location Referencing linear referencing
        system (LRS).

     INPUTS:
      in_feature_class (Feature Layer):
          The input LRS Network feature class to be modified.
      route_id_field {Field}:
          The field in the input feature class that will be mapped as
          the LRS Network route ID. The field type must match thefield type of
          the Centerline_Sequence table and must either be a string or GUID
          field type. RouteId
      route_name_field {Field}:
          A string field in the input feature class that will be mapped as the
          LRS Network route name.
      from_date_field {Field}:
          A date field in the input feature class that will be mapped as the LRS
          Network from date.
      to_date_field {Field}:
          A date field in the input feature class that will be mapped as the LRS
          Network to date.
      derive_from_line_network {String}:
          Determines if the current LRS network will be configured as an LRS
          Derived Network.AS_IS-The current LRS Network derived property will
          not be changed.
          This is the default.DERIVE-The input LRS Derived Network will be
          modified to become an LRS
          Derived Network. The line network name parameter must also be provided
          to specify which LRS Network to derive from.DO_NOT_DERIVE-The input
          LRS Derived Network will be modified to no
          longer be an LRS Derived Network.
      line_network_name {String}:
          The name of the LRS Line Network to which the input LRS Derived
          Network will be registered. The input LRS Line Network must reside in
          the same geodatabase workspace and LRS as the LRS network feature
          class. This parameter is only used if the derive_from_line_network
          parameter is set to DERIVE.
      include_fields_to_support_lines {String}:
          Determines if the current LRS network will be configured to support
          lines.AS_IS-The current LRS Network line support property will not be
          changed. This is the default.INCLUDE-The input LRS Network will be
          modified to add support for
          lines. The line id field, line name field, and line order field
          parameters must also be provided, and valid fields to map to these
          parameters must exist in the LRS network feature
          class.DO_NOT_INCLUDE-The input LRS Network will be modified to remove
          support for lines.
      line_id_field {Field}:
          The field in the input feature class that will be mapped as
          the LRS Network line ID. This parameter is only used if the
          include_fields_to_support_lines parameter is set to INCLUDE. The field
          type must match thefield type of the Centerline_Sequence table and
          must either be a string of exactly 38 characters or a GUID field type.
          RouteId
      line_name_field {Field}:
          A string field in the input feature class that will be mapped as the
          LRS Network line name. This parameter is only used if the
          include_fields_to_support_lines parameter is set to INCLUDE.
      line_order_field {Field}:
          The field in the input feature class that will be mapped as the LRS
          Network line order. This parameter is only used if the
          include_fields_to_support_lines parameter is set to INCLUDE. This must
          be a long integer field type.
      route_id_configuration {String}:
          Determines the route ID configuration for an LRS Network.AS_IS-The
          current LRS Network route ID configuration will not be
          changed. This is the default.AUTOGENERATED_ROUTE_ID-The route ID field
          will be an autogenerated
          GUID, and the route name can be configured as an LRS
          field.SINGLE_FIELD_ROUTE_ID-Supported only for nonline
          networks.MULTI_FIELD_ROUTE_ID-Supported only for nonline networks.
          More than
          one field is needed to form the concatenated route ID.
      individual_route_id_fields {Field}:
          The individual fields in the in_feature_class that will be used to
          form the route ID. This parameter is only used if the
          route_id_configuration parameter's MULTI_FIELD_ROUTE_ID option is set.
          The fields must be either string or number integer field types.

        """