# Generated documentation for module arcpy.ca


class CellPhoneRecordsToFeatureClass(object):
    """
    Imports cell phone records from wireless network providers and associates those records with a cell site and sector feature classes as generated by the Cell Site Records To Feature Class tool based on identifier fields.
    """

    @property
    def description(self) -> str:
        return """

        CellPhoneRecordsToFeatureClass_ca(in_table, in_site_features, in_sector_features, out_site_feature_class, out_sector_feature_class, id_fields;id_fields..., subscriber_field, {destination_field}, {additional_id_fields;additional_id_fields...}, {start_time_field}, {duration_field}, {end_time_field}, {convert_utc}, {location_x_field}, {location_y_field}, {location_coordinate_system}, {out_call_points}, {start_timing_distance_field}, {end_timing_distance_field}, {timing_advance_unit}, {timing_band_width}, {out_timing_advance_bands})

        Imports cell phone records from wireless network providers and
        associates those records with a cell site and sector feature classes
        as generated by the Cell Site Records To Feature Class tool based on
        identifier fields.

     INPUTS:
      in_table (Table View):
          The input table containing call records or phone data event records
          provided by the wireless network provider.
      in_site_features (Feature Layer):
          The feature class containing cell site points generated by the Cell
          Site Records to Feature Class tool.
      in_sector_features (Feature Layer):
          The feature class containing cell site sectors generated by the Cell
          Site Records to Feature Class tool.
      id_fields (Value Table):
          Specifies the unique ID field type and the fields that will be added
          to the output feature. Use thetype when theparameter value has
          a unique identifier
          for all cell sector antennas. Use a combination of othervalues when
          theparameter value does not contain a universal unique identifier for
          all cell sector antennas. Unique IDInput Phone Records TableID
          TypeInput Phone Records TableID Type-The field name to be included in
          the output feature
          classes.Field-The name of the fields that uniquely identify the cell
          sector
          antennas. These will be added to the output feature class.
          options are as follows:        ID TypeUnique ID-Uniquely identifies a
          cell sector antennaSite ID-Uniquely
          identifies a cell siteSector ID-Uniquely identifies a cell
          sectorSwitch ID-Uniquely identifies a wireless network switchLAC
          ID-Uniquely identifies the Location Area CodeCascade ID-Uniquely
          identifies the sector in the wireless network
          cascadeCell ID-Identifies the sector within an Location Area Code
      subscriber_field (Field):
          The field in the input table that contains the phone number or
          identifier of the subscriber.
      destination_field {Field}:
          The field in the input table that contains the phone number or
          identifier of the callee.
      additional_id_fields {Value Table}:
          Specifies the additional unique ID field type and the fields that will
          be added to the output feature. Use thetype when theparameter
          value has a unique identifier
          for all cell sector antennas. Use a combination of othervalues when
          theparameter value does not contain a universal unique identifier for
          all cell sector antennas. Unique IDInput Phone Records TableID
          TypeInput Phone Records TableID Type-The field name to be included in
          the output feature
          classes.Field-The name of the fields that uniquely identify the cell
          sector
          antennas. These will be added to the output feature class.
          options are as follows:        ID TypeUnique ID-Uniquely identifies a
          cell sector antennaSite ID-Uniquely
          identifies a cell siteSector ID-Uniquely identifies a cell
          sectorSwitch ID-Uniquely identifies a wireless network switchLAC
          ID-Uniquely identifies the Location Area CodeCascade ID-Uniquely
          identifies the sector in the wireless network
          cascadeCell ID-Identifies the sector within an Location Area Code
      start_time_field {Field}:
          The field in the input table that contains the start date and time
          field of the phone call or data event.
      duration_field {Field}:
          The field in the input table that contains the duration of the phone
          call in seconds.
      end_time_field {Field}:
          The field in the input table that contains the end date and time of
          the phone call or data event.
      convert_utc {Boolean}:
          Specifies whether the start and end date and time of the input records
          will be converted to the time zone of the local system or will remain
          in coordinated universal time (UTC).CONVERT-The start and end date and
          time of the input records will be
          converted from UTC to the time zone of the local system.NO_CONVERT-The
          start and end date and time of the input records will
          not be converted. This is the default.
      location_x_field {Field}:
          The field in the input table that contains the x-coordinate of the
          estimated phone location as provided by the wireless network provider.
      location_y_field {Field}:
          The field in the input table that contains the y-coordinate of the
          estimated phone location as provided by the wireless network provider.
      location_coordinate_system {Coordinate System}:
          The estimated phone location coordinate system of the x,y-coordinates.
          The default coordinate system is WGS84.
      start_timing_distance_field {Field}:
          The field in the input table that contains the timing advance distance
          at the start of the call.
      end_timing_distance_field {Field}:
          The field in the input table that contains the timing advance distance
          at the end of the call.
      timing_advance_unit {String}:
          Specifies the linear unit of measurement that will be used for
          the start_timing_distance_field andparameter values. End Timing
          Advance Distance FieldKILOMETERS-The unit will be
          kilometers.METERS-The unit will be
          meters.MILESINT-The unit will be statute miles.YARDSINT-The unit will
          be international yards.FEETINT-The unit will be international
          feet.MILES-The unit will be US Survey miles. This is the
          default.YARDS-The unit will be US Survey yards.FEET-The unit will be
          US Survey feet.
      timing_band_width {Linear Unit}:
          The full width of the timing advance band.The default is 78.07 meters.

     OUTPUTS:
      out_site_feature_class (Feature Class):
          The point feature class containing phone record site points.One point
          will be generated per phone record linked to cell site
          points.
      out_sector_feature_class (Feature Class):
          The polygon feature class containing phone record sectors.One sector
          polygon will be generated per phone record linked to cell
          site sectors.
      out_call_points {Feature Class}:
          The point feature class containing the estimated call locations as
          provided by the wireless network provider.
      out_timing_advance_bands {Feature Class}:
          The polygon feature class that will contain the timing advance bands
          as provided by the wireless network provider.

        """